/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StaffCredentials = IDL.Record({
  'userId' : IDL.Text,
  'password' : IDL.Text,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const AppointmentRequest = IDL.Record({
  'status' : AppointmentStatus,
  'email' : IDL.Opt(IDL.Text),
  'childAge' : IDL.Nat,
  'preferredDate' : IDL.Int,
  'preferredTime' : IDL.Text,
  'submissionTime' : IDL.Int,
  'phoneNumber' : IDL.Text,
  'childName' : IDL.Text,
  'parentName' : IDL.Text,
  'reason' : IDL.Text,
});
export const ActivationStatus = IDL.Variant({
  'activated' : IDL.Null,
  'deleted' : IDL.Null,
  'deactivated' : IDL.Null,
});
export const StaffUser = IDL.Record({
  'status' : ActivationStatus,
  'userId' : IDL.Text,
  'password' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateStaff' : IDL.Func([StaffCredentials], [IDL.Bool], []),
  'createAppointment' : IDL.Func([AppointmentRequest], [], []),
  'createStaffUser' : IDL.Func([StaffUser], [], []),
  'deactivateStaffUser' : IDL.Func([IDL.Text], [], []),
  'deleteStaffUser' : IDL.Func([IDL.Text], [], []),
  'getAllActiveStaffUsers' : IDL.Func([], [IDL.Vec(StaffUser)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeletedStaffUsers' : IDL.Func([], [IDL.Vec(StaffUser)], ['query']),
  'getInactiveStaffUsers' : IDL.Func([], [IDL.Vec(StaffUser)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAppointments' : IDL.Func([], [IDL.Vec(AppointmentRequest)], ['query']),
  'logoutStaff' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
  'updateStaffUser' : IDL.Func([IDL.Text, StaffUser], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StaffCredentials = IDL.Record({
    'userId' : IDL.Text,
    'password' : IDL.Text,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const AppointmentRequest = IDL.Record({
    'status' : AppointmentStatus,
    'email' : IDL.Opt(IDL.Text),
    'childAge' : IDL.Nat,
    'preferredDate' : IDL.Int,
    'preferredTime' : IDL.Text,
    'submissionTime' : IDL.Int,
    'phoneNumber' : IDL.Text,
    'childName' : IDL.Text,
    'parentName' : IDL.Text,
    'reason' : IDL.Text,
  });
  const ActivationStatus = IDL.Variant({
    'activated' : IDL.Null,
    'deleted' : IDL.Null,
    'deactivated' : IDL.Null,
  });
  const StaffUser = IDL.Record({
    'status' : ActivationStatus,
    'userId' : IDL.Text,
    'password' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateStaff' : IDL.Func([StaffCredentials], [IDL.Bool], []),
    'createAppointment' : IDL.Func([AppointmentRequest], [], []),
    'createStaffUser' : IDL.Func([StaffUser], [], []),
    'deactivateStaffUser' : IDL.Func([IDL.Text], [], []),
    'deleteStaffUser' : IDL.Func([IDL.Text], [], []),
    'getAllActiveStaffUsers' : IDL.Func([], [IDL.Vec(StaffUser)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeletedStaffUsers' : IDL.Func([], [IDL.Vec(StaffUser)], ['query']),
    'getInactiveStaffUsers' : IDL.Func([], [IDL.Vec(StaffUser)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAppointments' : IDL.Func([], [IDL.Vec(AppointmentRequest)], ['query']),
    'logoutStaff' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAppointmentStatus' : IDL.Func([IDL.Nat, AppointmentStatus], [], []),
    'updateStaffUser' : IDL.Func([IDL.Text, StaffUser], [], []),
  });
};

export const init = ({ IDL }) => { return []; };